# Generated by Django 6.0.4 on 2026-04-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jugador', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.CharField(max_length=50)),
                ('valoracion', models.IntegerField()),
                ('estilo_juego', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('pie', models.CharField(max_length=20)),
                ('stats_extra', models.JSONField(default=dict)),
                ('equipo_original', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_originales', to='core.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_traspaso', models.IntegerField(default=50000000)),
                ('presupuesto_salarial', models.IntegerField(default=2000000)),
                ('primer_login_completado', models.BooleanField(default=False)),
                ('equipo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
                ('opcion1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion1', to='core.team')),
                ('opcion2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion2', to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
