# Generated by Django 6.0.4 on 2026-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado_eleccion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('negado', 'Negado')], default='pendiente', max_length=20),
        ),
    ]
