# Generated by Django 6.0.4 on 2026-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_estado_eleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado_eleccion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('negado', 'Negado - Puede volver a elegir')], default='pendiente', max_length=20),
        ),
    ]
