# Generated by Django 6.0.4 on 2026-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transferoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='presupuesto_salarial',
            field=models.BigIntegerField(default=3500000000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='presupuesto_traspaso',
            field=models.BigIntegerField(default=3500000000),
        ),
    ]
