# Generated by Django 6.0.4 on 2026-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_presupuesto_salarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='en_mercado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='precio_calculado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='salario_anual',
            field=models.BigIntegerField(default=0),
        ),
    ]
