# Generated by Django 6.0.4 on 2026-04-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_en_mercado_player_precio_calculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='equipo_original_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_backup', to='core.team'),
        ),
    ]
